(use-package boon
  :config
  (require 'boon-qwerty)
  (boon-mode)
  (define-key boon-command-map "m" 'boon-toggle-comment)
  (define-key boon-command-map "C" 'my-copy-to-next-window)
  (define-key boon-command-map "S" 'save-buffer)
  (define-key boon-command-map "T" 'perspective-exwm-switch-perspective)
  (define-key boon-command-map "U" 'undo)
  (define-key boon-command-map "A" 'copy-edit)
  (define-key boon-command-map ":" 'add-semicolon)
  ;; (define-key boon-command-map "v" 'set-mark-command)
  ;; (define-key boon-command-map (kbd "SPC") 'boon-set-insert-like-state)
  (global-set-key [f2] 'boon-local-mode)
  ;; (global-set-key (kbd "C-SPC") 'boon-set-command-state)
  (add-hook 'sly-db-hook 'turn-off-boon-mode)
  (add-hook 'sly-mrepl-hook 'turn-off-boon-mode)
  (global-set-key [f2] 'boon-local-mode)
  (add-hook 'sly-db-hook 'turn-off-boon-mode)
  (add-hook 'sly-mrepl-hook 'turn-off-boon-mode)
  (add-hook 'eshell-mode-hook 'turn-off-boon-mode)
  (add-hook 'vterm-mode-hook 'turn-off-boon-mode)
  (add-hook 'geiser-debug-mode-hook 'turn-off-boon-mode)
  (add-hook 'geiser-repl-mode-hook 'turn-off-boon-mode)
  (add-hook 'eat-mode-hook 'turn-off-boon-mode)
  (add-hook 'after-save-hook 'boon-set-command-state)
  (add-hook 'gud-mode-hook 'turn-off-boon-mode))
